local bs = byte_span.new(4, 5)
bs:sub(1, 5)[5] = 33
bs:copy('hello')
print(#bs)
print(bs.capacity)
print(bs)
bs = bs:sub(1, 5)
print(#bs)
print(bs.capacity)
print(bs)
bs:copy('hello')
print(bs)
bs:sub(2):copy(bs)
print(bs)
bs:copy(bs:sub(2))
print(bs)
