-- Cancel on join

fib = spawn(function()
    local f2 = spawn(function()
        fib:cancel()
    end)
    print('foo')
    local ok = pcall(function()
        f2:join()
        print('bar')
    end)
    print(ok)
    this_fiber.disable_cancellation()
    local ok = pcall(function()
        this_fiber.restore_cancellation()
        f2:join()
    end)
    print(ok)
    this_fiber.disable_cancellation()
    f2:join()
    print('baz')
    f2:join() --< now invalid
    print('qux')
end)
