= libc_service.master

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

endif::[]

== Synopsis

[source,lua]
----
local libc_service = require "libc_service"
----

The master arbiters calls to libc that are related to ambient authority in the
process holding the slave end. Before a call to the real libc is attempted in
the slave end, the process forwards the request to the master and blocks the
thread until a reply is received.

The protocol follows the request-reply model. Low-level protocol details are
hidden by the Emilua runtime and the Lua programmer only sees a request-reply
API.

Multiplexing is not allowed. That means only one thread from the slave end can
be served at anytime and this layout will minimize the opportunity for possible
parallelism if the process holding the slave end makes too many calls for
ambient authority access. As a hidden implementation detail, Emilua will
transparently pipeline requests from different threads to minimize latency a
little.

== Functions

=== `receive(self)`

Receive the next attempted libc call for ambient authority.

Data about the call is stored in the object's properties.

=== `send(self, result: value, errno: integer|generic_error|system_error = 0)`

Send the result for the currently arbitrated libc call.

=== `send_with_fds(self, result: value, fds: file_descriptor[], errno: integer|generic_error|system_error = 0)`

Send the result for the currently arbitrated libc call.

=== `use_slave_credentials(self)`

Forward the request to the real libc running in the slave end.

=== `arguments(self) -> value...`

The arguments passed to the last requested call.

The arguments depend on the called function (see the property `function_`
below).

`open`::

`path: filesystem.path`::: The file path.

`flags: string[]`::: The open flags.
+
`flags` may contain:

`"append"`:::: Open the file in append mode.

`"create"`:::: Create the file if it does not exist.

`"directory"`:::: If pathname is not a directory, cause the open to fail.

`"exclusive"`:::: Ensure a new file is created. Must be combined with create.

`"read_only"`:::: Open the file for reading.

`"read_write"`:::: Open the file for reading and writing.

`"sync_all_on_write"`:::: Open the file so that write operations automatically
synchronise the file data and metadata to disk
(`FILE_FLAG_WRITE_THROUGH`/`O_SYNC`).

`"temporary"`:::: Create an unnamed temporary regular file.

`"truncate"`:::: Open the file with any existing contents truncated.

`"write_only"`:::: Open the file for writing.

`mode: integer`::: Optional argument. Only present if `"create"` or
`"temporary"` appear in `flags`.

`connect_unix`::

`path: filesystem.path`::: The UNIX socket path.

`connect_inet`::

`ipv4_addr: ip.address`::: The IPv4 address.

`port: integer`::: The port.

=== `descriptors(self) -> file_descriptor...`

Extract and return the file descriptors received with the last requested call.

NOTE: Once you call this function, the returned descriptors no longer stay
stored in this object. IOW, a second call to this function will always return
nothing.

== Properties

=== `function_: string`

The last requested call.

Possible values:

* `"open"`
* `"connect_unix"`
* `"connect_inet"`
