= unix.seqpacket.acceptor

ifeval::["{doctype}" == "manpage"]

== Name

Emilua - Lua execution engine

== Synopsis

endif::[]

[source,lua]
----
local a = unix.seqpacket.acceptor.new()
a:open()
a:bind(filesystem.path.new('/tmp/9Lq7BNBnBycd6nxy.socket'))
a:listen()

while true do
    local s = a:accept()
    spawn(function()
        my_client_handler(s)
    end)
end
----

== Functions

=== `new() -> unix.seqpacket.acceptor`

[source,lua]
----
new()                    -- <1>
new(fd: file_descriptor) -- <2>
----
<1> Default constructor.
<2> Converts a file descriptor into an `unix.seqpacket.acceptor` object.

=== `open(self)`

Open the acceptor.

=== `set_option(self, opt: string, val)`

Set an option on the acceptor.

Currently available options are:

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

=== `get_option(self, opt: string) -> value`

Get an option from the acceptor.

Currently available options are:

`"enable_connection_aborted"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/enable_connection_aborted.html[Check
Boost.Asio documentation].

`"debug"`::
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/socket_base/debug.html[Check
Boost.Asio documentation].

=== `bind(self, pathname: filesystem.path)`

Bind the acceptor to the given local endpoint.

=== `listen(self [, backlog: integer])`

Place the acceptor into the state where it will listen for new connections.

`backlog` is the maximum length of the queue of pending connections. If not
provided, an implementation defined maximum length will be used.

=== `accept(self) -> unix.seqpacket.socket`

Initiate an accept operation and blocks current fiber until it completes or
errs.

=== `wait(self, wait_type: "read"|"write"|"error")`

Wait for the socket to become ready to read, ready to write, or to have pending
error conditions.

In short, the reactor model is exposed on top of the proactor model.

IMPORTANT: You shouldn't be using reactor-style operations on Emilua. However if
you're trying to compete against systemD (or just xinetd) implementing a service
manager employing socket activation then you'll need the readiness event to
trigger the managed service startup sequence.

`wait_type` can be one of the following:

`"read"`:: Wait for a socket to become ready to read.
`"write"`:: Wait for a socket to become ready to write.
`"error"`:: Wait for a socket to have error conditions pending.

=== `close(self)`

Close the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/close/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
Any asynchronous accept operations will be cancelled immediately.

A subsequent call to open() is required before the acceptor can again be used to
again perform socket accept operations.
____

=== `cancel(self)`

Cancel all asynchronous operations associated with the acceptor.

Forward the call to
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_socket_acceptor/cancel/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous connect, send and receive
operations to finish immediately, and the handlers for cancelled operations will
be passed the `boost::asio::error::operation_aborted` error.
____

=== `assign(self, fd: file_descriptor)`

Assign an existing native acceptor to `self`.

=== `release(self) -> file_descriptor`

Release ownership of the native descriptor implementation.

Forward the call to
https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/basic_socket_acceptor/release/overload2.html[the
function with same name in Boost.Asio]:

[quote]
____
This function causes all outstanding asynchronous accept operations to finish
immediately, and the handlers for cancelled operations will be passed the
`boost::asio::error::operation_aborted` error. Ownership of the native acceptor
is then transferred to the caller.
____

== Properties

=== `is_open: boolean`

Whether the acceptor is open.

=== `local_path: filesystem.path`

The local address of the acceptor.
