baseURL = "https://vinipsmaker.gitlab.io/emilua/"
languageCode = "en-us"
title = "Emilua"

metaDataFormat = "toml"
theme = "beautifulhugo"

[Params]
subtitle = "Emilua is a fiber-based network framework for lua"

useHLJS = true

[[menu.main]]
name = "Tutorials(7)"
url = "tutorial/"
weight = 1

#[[menu.main]]
#name = "Reference(3)"
#url = "ref/"
#weight = 2
