// Copyright (c) 2024 Vinícius dos Santos Oliveira
// SPDX-License-Identifier: MIT OR BSL-1.0

#include <emilua/windows.hpp>
#include <emilua/state.hpp>

#include <fmt/ostream.h>
#include <fmt/format.h>

#include <boost/nowide/iostream.hpp>

namespace hana = boost::hana;
namespace fs = std::filesystem;

namespace emilua::main {

#if BOOST_OS_WINDOWS
extern int (*main)(int argc, char *argv[], char *envp[]);
#else // BOOST_OS_WINDOWS
int main(int argc, char *argv[], char *envp[]);
#endif // BOOST_OS_WINDOWS

static constexpr auto help_text = FMT_STRING(
    "Emilua: Execution engine for luaJIT\n"
    "Usage: {} [OPTIONS] [file]\n"
    "\n"
    "Positionals:\n"
    "  file TEXT                   Script filename\n"
    "\n"
    "Options:\n"
    "  -h,--help                   Print this help message and exit\n"
    "  --main-context-concurrency-hint INT\n"
    "                              Concurrency hint for the main execution engine context\n"
    "  --main-context-scheduler-task-usec INT\n"
    "                              The maximum time, in microseconds, that the scheduler will wait for its reactor task to complete.\n"
    "  --main-context-scheduler-wait-usec INT\n"
    "                              The maximum time, in microseconds, that the scheduler will wait on its wake-up event in an idle thread.\n"
    "  --main-context-reactor-preallocated-io-objects INT\n"
    "                              The number of internal reactor I/O object states to allocate at construction.\n"
    "  --test Run tests\n"
    "  --version                   Output version information and exit\n");

static std::string filename_buffer;
static std::string_view filename;
static config_from_cli main_ctx_service_maker_;
static ContextType main_context_type = ContextType::main;

#if BOOST_OS_WINDOWS
extern void (*parse_args)(int argc, char *argv[], app_context& appctx);
static void parse_args2(int argc, char *argv[], app_context& appctx)
#else // BOOST_OS_WINDOWS
void parse_args(int argc, char *argv[], app_context& appctx)
#endif // BOOST_OS_WINDOWS
{
#define NEXT_ARG(OPTION, LABEL) do {                           \
        if (YYCURSOR = *++cur_arg ; YYCURSOR != nullptr) {     \
            goto LABEL;                                        \
        } else {                                               \
            try {                                              \
                boost::nowide::cerr <<                         \
                    "missing value for option `" OPTION "`\n"; \
            } catch (const std::ios_base::failure&) {}         \
            std::exit(2);                                      \
        }                                                      \
    } while(0)

#define ERRARG(OPTION)                                                     \
    do {                                                                   \
        try {                                                              \
            fmt::print(                                                    \
                boost::nowide::cerr,                                       \
                FMT_STRING(                                                \
                    "value `{}` not supported for option `" OPTION "`\n"), \
                *cur_arg);                                                 \
        } catch (const std::ios_base::failure&) {}                         \
        std::exit(2);                                                      \
    } while(0)

    if (argc <= 0) {
        try {
            boost::nowide::cerr << "missing filename\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }

    /*!re2c
    re2c:define:YYCTYPE = char;
    re2c:yyfill:enable = 0;
    re2c:indent:string = "    ";

    end = "\x00";
    filename = [^\x00-][^\x00]*;
    unsigned_integer = [0-9]+;
    */
    char* YYCURSOR;
    char* YYMARKER;
    char** cur_arg = argv;
opt:
    YYCURSOR = *++cur_arg;
    if (YYCURSOR == nullptr) goto end;
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad option: `{}`\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    "--" {end} {
        appctx.app_args.reserve(2 + ((argv + argc) - (cur_arg + 1)));
        appctx.app_args.emplace_back(argv[0]);
        appctx.app_args.emplace_back(filename);
        while (*++cur_arg) {
            appctx.app_args.emplace_back(*cur_arg);
        }
        goto end;
    }
    "-" {end} {
        try {
            boost::nowide::cerr << "stdin not supported as input file\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    {filename} {end} {
        if (filename.size() > 0) {
            try {
                boost::nowide::cerr <<
                    "emilua doesn't support more than one input file\n";
            } catch (const std::ios_base::failure&) {}
            std::exit(2);
        }
        filename = *cur_arg;
        fs::path as_path{widen_on_windows(filename)};
        std::error_code ignored_ec;
        if (fs::is_directory(as_path, ignored_ec)) {
            // Alternatively, we could apply this transformation inside
            // `make_master_vm()`. However if the user is using
            // `modules_cache_registry` or `get_builtin_module()` the query
            // wouldn't make sense inside `make_master_vm()`. Here's the most
            // appropriate place to perform filesystem queries and apply such
            // transformations.
            as_path /= "init.lua";
            filename_buffer = as_path.string();
            filename = filename_buffer;
        }
        goto opt;
    }
    "-" { goto opt_short; }
    "--" { goto opt_long; }
    %}

opt_short:
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad short option: {}\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    {end} { goto opt; }
    "h" {
        try {
            fmt::print(boost::nowide::cout, help_text, *argv);
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    %}

opt_long:
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad long option: {}\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    "help" {end} {
        try {
            fmt::print(boost::nowide::cout, help_text, *argv);
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    "version" {end} {
        try {
            boost::nowide::cout << "Emilua " EMILUA_CONFIG_VERSION_STRING <<
                std::endl << LUAJIT_VERSION << std::endl <<
                "Boost " << (BOOST_VERSION / 100000) << '.' <<
                (BOOST_VERSION / 100 % 1000) << '.' << (BOOST_VERSION % 100) <<
                std::endl <<
#if EMILUA_CONFIG_USE_STANDALONE_ASIO
                "ASIO " << (ASIO_VERSION / 100000) << '.' <<
                (ASIO_VERSION / 100 % 1000) << '.' << (ASIO_VERSION % 100) <<
                std::endl <<
#endif // EMILUA_CONFIG_USE_STANDALONE_ASIO
                std::flush;
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    "main-context-concurrency-hint=" {
        *cur_arg = YYCURSOR;
        goto opt_main_context_concurrency_hint;
    }
    "main-context-concurrency-hint" {end} {
        NEXT_ARG("--main-context-concurrency-hint",
                 opt_main_context_concurrency_hint);
    }
    "main-context-scheduler-task-usec=" {
        *cur_arg = YYCURSOR;
        goto opt_scheduler_task_usec;
    }
    "main-context-scheduler-task-usec" {end} {
        NEXT_ARG("--main-context-scheduler-task-usec", opt_scheduler_task_usec);
    }
    "main-context-scheduler-wait-usec=" {
        *cur_arg = YYCURSOR;
        goto opt_scheduler_wait_usec;
    }
    "main-context-scheduler-wait-usec" {end} {
        NEXT_ARG("--main-context-scheduler-wait-usec", opt_scheduler_wait_usec);
    }
    "main-context-reactor-preallocated-io-objects=" {
        *cur_arg = YYCURSOR;
        goto opt_reactor_preallocated_io_objects;
    }
    "main-context-reactor-preallocated-io-objects" {end} {
        NEXT_ARG("--main-context-reactor-preallocated-io-objects",
                 opt_reactor_preallocated_io_objects);
    }
    "test" {end} {
        main_context_type = ContextType::test;
        goto opt;
    }
    %}

opt_main_context_concurrency_hint:
    %{
    * { ERRARG("--main-context-concurrency-hint"); }
    {unsigned_integer} {end} {
        std::string_view view = *cur_arg;
        int as_int;
        if (
            std::from_chars(view.data(), view.data() + view.size(), as_int).ec
            != std::errc{} || as_int > EMILUA_MAX_ASIO_CONCURRENCY_HINT
        ) {
            ERRARG("--main-context-concurrency-hint");
        }
        // from
        // https://www.boost.org/doc/libs/1_88_0/doc/html/boost_asio/overview/core/configuration.html#boost_asio.overview.core.configuration.configuration_from_concurrency_hint
        main_ctx_service_maker_.storage.scheduler_concurrency_hint = as_int;
        main_ctx_service_maker_.storage.scheduler_locking = true;
        main_ctx_service_maker_.storage.reactor_registration_locking = true;
        main_ctx_service_maker_.storage.reactor_io_locking = true;
        goto opt;
    }
    "unsafe-io" {end} {
        main_ctx_service_maker_.use_hint_unsafe_io();
        goto opt;
    }
    "unsafe" {end} {
        main_ctx_service_maker_.use_hint_unsafe();
        goto opt;
    }
    %}

opt_scheduler_task_usec:
    {
        std::string_view view = *cur_arg;
        int as_int;
        auto res = std::from_chars(
            view.data(), view.data() + view.size(), as_int);
        if (
            res.ec != std::errc{} || res.ptr != view.data() + view.size() ||
            (as_int < 0 && as_int != -1)
        ) {
            ERRARG("--main-context-scheduler-task-usec");
        }
        main_ctx_service_maker_.storage.scheduler_task_usec = as_int;
        goto opt;
    }

opt_scheduler_wait_usec:
    {
        std::string_view view = *cur_arg;
        int as_int;
        auto res = std::from_chars(
            view.data(), view.data() + view.size(), as_int);
        if (
            res.ec != std::errc{} || res.ptr != view.data() + view.size() ||
            (as_int < 0 && as_int != -1)
        ) {
            ERRARG("--main-context-scheduler-wait-usec");
        }
        main_ctx_service_maker_.storage.scheduler_wait_usec = as_int;
        goto opt;
    }

opt_reactor_preallocated_io_objects:
    {
        std::string_view view = *cur_arg;
        int as_int;
        auto res = std::from_chars(
            view.data(), view.data() + view.size(), as_int);
        if (
            res.ec != std::errc{} || res.ptr != view.data() + view.size() ||
            as_int < 0
        ) {
            ERRARG("--main-context-reactor-preallocated-io-objects");
        }
        main_ctx_service_maker_.storage.reactor_preallocated_io_objects =
            as_int;
        goto opt;
    }

end:

    if (filename.size() == 0) {
        try {
            boost::nowide::cerr << "missing filename\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }

    if (appctx.app_args.size() == 0) {
        appctx.app_args.reserve(2);
        appctx.app_args.emplace_back(argv[0]);
        appctx.app_args.emplace_back(filename);
    }
}

#if BOOST_OS_WINDOWS
extern
const asio::execution_context::service_maker& (*main_ctx_service_maker)();
static const asio::execution_context::service_maker& main_ctx_service_maker2()
#else // BOOST_OS_WINDOWS
const asio::execution_context::service_maker& main_ctx_service_maker()
#endif // BOOST_OS_WINDOWS
{
    return main_ctx_service_maker_;
}

#if BOOST_OS_WINDOWS
extern void (*make_master_vm)(app_context& appctx, asio::io_context& ioctx);
static void make_master_vm2(app_context& appctx, asio::io_context& ioctx)
#else // BOOST_OS_WINDOWS
void make_master_vm(app_context& appctx, asio::io_context& ioctx)
#endif // BOOST_OS_WINDOWS
{
    auto vm_ctx = make_vm(appctx, ioctx, main_context_type,
                          widen_on_windows(filename));
    appctx.master_vm = vm_ctx;
    vm_ctx->strand().post([vm_ctx]() {
        vm_ctx->fiber_resume(
            vm_ctx->L(),
            hana::make_set(vm_context::options::skip_clear_interrupter));
    }, std::allocator<void>{});
}

} // namespace emilua::main

int main(int argc, char *argv[], char *envp[])
{
#if BOOST_OS_WINDOWS
    emilua::main::parse_args = emilua::main::parse_args2;
    emilua::main::main_ctx_service_maker =
        emilua::main::main_ctx_service_maker2;
    emilua::main::make_master_vm = emilua::main::make_master_vm2;
#endif // BOOST_OS_WINDOWS
    return emilua::main::main(argc, argv, envp);
}
