// Copyright (c) 2024 Vinícius dos Santos Oliveira
// SPDX-License-Identifier: MIT OR BSL-1.0

#include <emilua/windows.hpp>
#include <emilua/state.hpp>

#include <fmt/ostream.h>
#include <fmt/format.h>

#include <boost/nowide/iostream.hpp>

namespace hana = boost::hana;
namespace fs = std::filesystem;

namespace emilua::main {

#if BOOST_OS_WINDOWS
extern int (*main)(int argc, char *argv[], char *envp[]);
#else // BOOST_OS_WINDOWS
int main(int argc, char *argv[], char *envp[]);
#endif // BOOST_OS_WINDOWS

static constexpr auto help_text = FMT_STRING(
    "Emilua: Execution engine for luaJIT\n"
    "Usage: {} [OPTIONS] [file]\n"
    "\n"
    "Positionals:\n"
    "  file TEXT                   Script filename\n"
    "\n"
    "Options:\n"
    "  -h,--help                   Print this help message and exit\n"
    "  --main-context-concurrency-hint INT\n"
    "                              Concurrency hint for the main execution engine context\n"
    "  --test Run tests\n"
    "  --version                   Output version information and exit\n");

static std::string filename_buffer;
static std::string_view filename;
static int main_ctx_concurrency_hint_ = 0;
static ContextType main_context_type = ContextType::main;

#if BOOST_OS_WINDOWS
extern void (*parse_args)(int argc, char *argv[], app_context& appctx);
static void parse_args2(int argc, char *argv[], app_context& appctx)
#else // BOOST_OS_WINDOWS
void parse_args(int argc, char *argv[], app_context& appctx)
#endif // BOOST_OS_WINDOWS
{
#define NEXT_ARG(OPTION, LABEL) do {                           \
        if (YYCURSOR = *++cur_arg ; YYCURSOR != nullptr) {     \
            goto LABEL;                                        \
        } else {                                               \
            try {                                              \
                boost::nowide::cerr <<                         \
                    "missing value for option `" OPTION "`\n"; \
            } catch (const std::ios_base::failure&) {}         \
            std::exit(2);                                      \
        }                                                      \
    } while(0)

#define ERRARG(OPTION)                                                     \
    do {                                                                   \
        try {                                                              \
            fmt::print(                                                    \
                boost::nowide::cerr,                                       \
                FMT_STRING(                                                \
                    "value `{}` not supported for option `" OPTION "`\n"), \
                *cur_arg);                                                 \
        } catch (const std::ios_base::failure&) {}                         \
        std::exit(2);                                                      \
    } while(0)

    if (argc <= 0) {
        try {
            boost::nowide::cerr << "missing filename\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }

    /*!re2c
    re2c:define:YYCTYPE = char;
    re2c:yyfill:enable = 0;
    re2c:indent:string = "    ";

    end = "\x00";
    filename = [^\x00-][^\x00]*;
    */
    char* YYCURSOR;
    char* YYMARKER;
    char** cur_arg = argv;
opt:
    YYCURSOR = *++cur_arg;
    if (YYCURSOR == nullptr) goto end;
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad option: `{}`\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    "--" {end} {
        appctx.app_args.reserve(2 + ((argv + argc) - (cur_arg + 1)));
        appctx.app_args.emplace_back(argv[0]);
        appctx.app_args.emplace_back(filename);
        while (*++cur_arg) {
            appctx.app_args.emplace_back(*cur_arg);
        }
        goto end;
    }
    "-" {end} {
        try {
            boost::nowide::cerr << "stdin not supported as input file\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    {filename} {end} {
        if (filename.size() > 0) {
            try {
                boost::nowide::cerr <<
                    "emilua doesn't support more than one input file\n";
            } catch (const std::ios_base::failure&) {}
            std::exit(2);
        }
        filename = *cur_arg;
        fs::path as_path{widen_on_windows(filename)};
        std::error_code ignored_ec;
        if (fs::is_directory(as_path, ignored_ec)) {
            // Alternatively, we could apply this transformation inside
            // `make_master_vm()`. However if the user is using
            // `modules_cache_registry` or `get_builtin_module()` the query
            // wouldn't make sense inside `make_master_vm()`. Here's the most
            // appropriate place to perform filesystem queries and apply such
            // transformations.
            as_path /= "init.lua";
            filename_buffer = as_path.string();
            filename = filename_buffer;
        }
        goto opt;
    }
    "-" { goto opt_short; }
    "--" { goto opt_long; }
    %}

opt_short:
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad short option: {}\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    {end} { goto opt; }
    "h" {
        try {
            fmt::print(boost::nowide::cout, help_text, *argv);
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    %}

opt_long:
    %{
    * {
        try {
            fmt::print(boost::nowide::cerr, FMT_STRING("bad long option: {}\n"),
                       *cur_arg);
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }
    "help" {end} {
        try {
            fmt::print(boost::nowide::cout, help_text, *argv);
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    "version" {end} {
        try {
            boost::nowide::cout << "Emilua " EMILUA_CONFIG_VERSION_STRING <<
                std::endl << LUAJIT_VERSION << std::endl <<
                "Boost " << (BOOST_VERSION / 100000) << '.' <<
                (BOOST_VERSION / 100 % 1000) << '.' << (BOOST_VERSION % 100) <<
                std::endl <<
#if EMILUA_CONFIG_USE_STANDALONE_ASIO
                "ASIO " << (ASIO_VERSION / 100000) << '.' <<
                (ASIO_VERSION / 100 % 1000) << '.' << (ASIO_VERSION % 100) <<
                std::endl <<
#endif // EMILUA_CONFIG_USE_STANDALONE_ASIO
                std::flush;
        } catch (const std::ios_base::failure&) {}
        std::exit(0);
    }
    "main-context-concurrency-hint=" {
        *cur_arg = YYCURSOR;
        goto opt_main_context_concurrency_hint;
    }
    "main-context-concurrency-hint" {end} {
        NEXT_ARG("--main-context-concurrency-hint",
                 opt_main_context_concurrency_hint);
    }
    "test" {end} {
        main_context_type = ContextType::test;
        goto opt;
    }
    %}

opt_main_context_concurrency_hint:
    %{
    * { ERRARG("--main-context-concurrency-hint"); }
    "0" {end} {
        main_ctx_concurrency_hint_ = 0;
        goto opt;
    }
    "1" {end} {
        main_ctx_concurrency_hint_ = 1;
        goto opt;
    }
    "safe" {end} {
#if EMILUA_CONFIG_USE_STANDALONE_ASIO
        main_ctx_concurrency_hint_ = ASIO_CONCURRENCY_HINT_SAFE;
#else // EMILUA_CONFIG_USE_STANDALONE_ASIO
        main_ctx_concurrency_hint_ = BOOST_ASIO_CONCURRENCY_HINT_SAFE;
#endif // EMILUA_CONFIG_USE_STANDALONE_ASIO
        goto opt;
    }
    %}
end:

    if (filename.size() == 0) {
        try {
            boost::nowide::cerr << "missing filename\n";
        } catch (const std::ios_base::failure&) {}
        std::exit(2);
    }

    if (appctx.app_args.size() == 0) {
        appctx.app_args.reserve(2);
        appctx.app_args.emplace_back(argv[0]);
        appctx.app_args.emplace_back(filename);
    }
}

#if BOOST_OS_WINDOWS
extern int (*main_ctx_concurrency_hint)();
static int main_ctx_concurrency_hint2()
#else // BOOST_OS_WINDOWS
int main_ctx_concurrency_hint()
#endif // BOOST_OS_WINDOWS
{
    return main_ctx_concurrency_hint_;
}

#if BOOST_OS_WINDOWS
extern void (*make_master_vm)(
    app_context& appctx, std::shared_ptr<asio::io_context> ioctx);
static void make_master_vm2(
    app_context& appctx, std::shared_ptr<asio::io_context> ioctx)
#else // BOOST_OS_WINDOWS
void make_master_vm(
    app_context& appctx, std::shared_ptr<asio::io_context> ioctx)
#endif // BOOST_OS_WINDOWS
{
    auto vm_ctx = make_vm(*ioctx, appctx, main_context_type,
                          widen_on_windows(filename));
    vm_ctx->ioctxref = ioctx;
    appctx.master_vm = vm_ctx;
    vm_ctx->strand().post([vm_ctx]() {
        vm_ctx->fiber_resume(
            vm_ctx->L(),
            hana::make_set(vm_context::options::skip_clear_interrupter));
    }, std::allocator<void>{});
}

} // namespace emilua::main

int main(int argc, char *argv[], char *envp[])
{
#if BOOST_OS_WINDOWS
    emilua::main::parse_args = emilua::main::parse_args2;
    emilua::main::main_ctx_concurrency_hint =
        emilua::main::main_ctx_concurrency_hint2;
    emilua::main::make_master_vm = emilua::main::make_master_vm2;
#endif // BOOST_OS_WINDOWS
    return emilua::main::main(argc, argv, envp);
}
